<section class="cob-fsCal-container">
    <section class="cob-fsCal">
        <h1 class="cob-dateHeader">
            <span class="cob-dateHeader-weekday">Monday</span>
            <span class="cob-dateHeader-month">November</span>
            <span class="cob-dateHeader-monthDate">31</span>
        </h1>
        <article class="cob-event">
            <h1 class="cob-event-title">Event Title Bloomington Advisory Committee Board</h1>
            <time>8:00pm</time>
            <a href="#" class="cob-icon-calendar" title="View on Google Calendar">View on Google Calendar</a>
            <div class="cob-event-meta">
                <div class="cob-event-location">City Hall McCloskey Room</div>
            </div>
            <div class="cob-event-description">
                <p>Community Condition addresses a broad range of issues often best addressed by municipal government. Issues that impact the human condition, our animals and the community at large include public safety.</p>
            </div>
        </article>

        <article class="cob-event">
            <h1 class="cob-event-title">Event Title Bloomington Advisory Committee Board</h1>
            <time>8:00pm</time>
            <a href="#" class="cob-icon-calendar" title="View on Google Calendar">View on Google Calendar</a>
            <div class="cob-event-meta">
                <div class="cob-event-location">City Hall McCloskey Room</div>
            </div>
            <div class="cob-event-description">
                <p>Community Condition addresses a broad range of issues often best addressed by municipal government. Issues that impact the human condition, our animals and the community at large include public safety.</p>
            </div>
        </article>
    </section>

    <section class="cob-fsCal">
        <h1 class="cob-dateHeader">
            <span class="cob-dateHeader-weekday">Monday</span>
            <span class="cob-dateHeader-month">November</span>
            <span class="cob-dateHeader-monthDate">31</span>
        </h1>
        <article class="cob-event">
            <h1>Event Title Bloomington Advisory Committee Board</h1>
            <time>8:00pm</time>
            <a href="#" class="cob-icon-calendar" title="View on Google Calendar">View on Google Calendar</a>
            <div class="cob-event-meta">
                <div class="cob-event-location">City Hall McCloskey Room</div>
            </div>
            <div class="cob-event-description">
                <p>Community Condition addresses a broad range of issues often best addressed by municipal government. Issues that impact the human condition, our animals and the community at large include public safety.</p>
            </div>
        </article>
        <article class="cob-event">
            <h1>Event Title Bloomington Advisory Committee Board</h1>
            <time>8:00pm</time>
            <a href="#" class="cob-icon-calendar" title="View on Google Calendar">View on Google Calendar</a>
            <div class="cob-event-meta">
                <div class="cob-event-location">City Hall McCloskey Room</div>
            </div>
            <div class="cob-event-description">
                <p>Community Condition addresses a broad range of issues often best addressed by municipal government. Issues that impact the human condition, our animals and the community at large include public safety.</p>
            </div>
        </article>
    </section>
</section>
